model:
    name: 'SelfSupModel'
    depth_net:
        name: 'Spike_PackNet01'
        version: '1A2B'
        #forward_single: False
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    test:
        dataset: ['Spike_KITTI']
        path: ['/data1/lijianing/Data/KITTI/KITTI_raw/']
        split: ['data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']
save:
    folder: '/data1/lijianing/code/spike/packnet-sfm/save'
    depth:
        rgb: True
        viz: True
        npz: True
        png: True
