model:
    #checkpoint_path: './ckpt/default_config-train_kitti_spike_distill-2023.10.16-14h23m33s/epoch=18_-eigen_val_files-velodyne-loss=0.000.ckpt' #"./epoch=09_-eigen_val_files-velodyne-loss=0.000.ckpt" #
    checkpoint_path: "./epoch=09_-eigen_val_files-velodyne-loss=0.000.ckpt"
    name: 'Spik_SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'Spike_PackNet01'
        version: '1A2B3D'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 2 
        dataset: ['Spike_KITTI']
        path: ['/data1/lijianing/Data/KITTI/KITTI_raw/']
        split: ['data_splits/eigen_zhou_files.txt']
        depth_type: ['velodyne']
        repeat: [2]
    validation:
        batch_size: 1
        dataset: ['Spike_KITTI']
        path: ['/data1/lijianing/Data/KITTI/KITTI_raw/']
        split: ['data_splits/eigen_val_files.txt',
                'data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['Spike_KITTI']
        path: ['/data1/lijianing/Data/KITTI/KITTI_raw/']
        split: ['data_splits/spike_inference_v2.txt']    #data_splits/kitti_test_files.txt
        depth_type: ['velodyne']
    
